name: Bug report
description: File a bug report
title: "[Bug]: "
labels: [ "bug", "triage" ]
projects: [ "Brancieq-Paul/2" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much information as possible to help us reproduce and fix the issue.
  - type: textarea
    id: explication
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
  - type: dropdown
    id: OS
    attributes:
      label: OS
      description: What OS are you using?
      options:
        - Windows
        - MacOS
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: precision
    attributes:
      label: Precise OS if other
      description: If you selected "Other" in the previous question, please tell us what OS you are using.
      placeholder: Not windows, not mac, not linux? Tell us!
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: origin
    attributes:
      label: Check before submitting
      description: Please check the following before submitting your bug report
      options:
        - label: I have searched the open and closed issues for duplicates
          required: true
        - label: I have checked the documentation and found no answer
          required: true
        - label: I have checked the latest version of the mod
          required: true