name: Feature request
description: File a feature request
title: "[Feature Request]: "
labels: [ "enhancement", "triage" ]
projects: [ "Brancieq-Paul/2" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please provide as much information as possible to help us understand your request.
  - type: textarea
    id: explication
    attributes:
      label: Describe the feature request
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        **Describe the feature request**
        A clear and concise description of what the feature request is.
            
        **Screenshots/Images**
        If applicable, add screenshots to help explain your feature request.