name: Repo and documentation issue
description: File an issue/request with the repository or documentation
title: "[Repo/Docs]: "
labels: [ "repository", "documentation", "triage" ]
projects: [ "Brancieq-Paul/2" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue/request! Please provide as much information as possible to help us understand your request.
  - type: textarea
    id: explication
    attributes:
      label: Describe the issue/request
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        **Describe the issue/request**
        A clear and concise description of what the issue/request is.